# Generated by Django 5.2.2 on 2025-06-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_alter_phone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
